### ISSUE TITLE
Kernel compilation fails - error: field has incomplete type 'struct msm_hwacc_effects_config'

### ISSUE THREAD

**Issue by upyisfar** [upyisfar/android_device_alcatel_idol3#1]
In file included from hardware/qcom/audio-caf/msm8916/post_proc/bundle.c:48:
hardware/qcom/audio-caf/msm8916/post_proc/hw_accelerator.h:48:37: error: field has incomplete type 'struct msm_hwacc_effects_config'
    struct msm_hwacc_effects_config cfg;
                                    ^
hardware/qcom/audio-caf/msm8916/post_proc/hw_accelerator.h:48:12: note: forward declaration of 'struct msm_hwacc_effects_config'
    struct msm_hwacc_effects_config cfg;
           ^
hardware/qcom/audio-caf/msm8916/post_proc/bundle.c:461:62: warning: unused parameter 'query' [-Wunused-parameter]
void offload_effects_bundle_get_parameters(struct str_parms *query,
                                                             ^
hardware/qcom/audio-caf/msm8916/post_proc/bundle.c:462:62: warning: unused parameter 'reply' [-Wunused-parameter]
                                           struct str_parms *reply)
                                                             ^
hardware/qcom/audio-caf/msm8916/post_proc/bundle.c:468:62: warning: unused parameter 'parms' [-Wunused-parameter]
void offload_effects_bundle_set_parameters(struct str_parms *parms)
                                                             ^
4 warnings and 1 error generated.

**Comment by upyisfar** [comment]
CCompilation continues when skipping post_proc in the audio-caf module. It is unclear what impact this can have other than audio post processing being unavailable. HW effects processing components seems to have been from the kernel possibly due to security vulnerabilies that were found.

**Comment by vknecht** [comment]
You could try older kernels with previous CAF update like [3.10.68/cafrb141](https://github.com/vknecht/android_kernel_alcatel_msm8916/commits/upstream-lxstable) or [3.10.49/cafrb141](https://github.com/vknecht/android_kernel_alcatel_msm8916/commits/cm-14.1-new), but I guess the real fix would be to find and merge some newer CAF tag for hadware/ if that exists (didn't look, just thought about it for wifi and some other part, when reading the commit history)...
